Add prepared statements and apis for calendar/profile page
Navkiran23/DubSpot pull request #69
Opened 2023-05-18 22:01 UTC by dennywu84

2023-05-21 06:23 UTC, bytehut requested changes
We also need a prepared statement to fetch the profile information, and an app.post that receives information from the client that calls the updateProfilePage

2023-05-21 06:23 UTC, bytehut commented on Backend/index.js
> +const {pool, getCourseStatement, getReviewsStatement, addReviewStatement, createAccountStatement, loginAccountStatement, findPlannedClassesStatement, updateProfilePage} = require("./sql")
should rename updateProfilePage to include 'Statement' for consistency

2023-05-21 06:23 UTC, bytehut commented on Backend/index.js
> +  } else {
could return a 401 unauthorized status instead

2023-05-21 06:23 UTC, bytehut commented on Backend/index.js
> +  res.sendFile(path.join(root, 'FrontEnd', 'DubSpotCalendar.html'))
shouldnt send the html file here

2023-05-21 06:23 UTC, bytehut commented on Backend/index.js
> +  res.sendFile(path.join(root, 'FrontEnd', 'DubSpotProfile.html'))
shouldnt send the html file here

2023-05-23 07:25 UTC, dennywu84 commented on Backend/index.js
> +  res.sendFile(path.join(root, 'FrontEnd', 'DubSpotProfile.html'))
Fixed

2023-05-23 07:25 UTC, dennywu84 commented on Backend/index.js
> +  res.sendFile(path.join(root, 'FrontEnd', 'DubSpotCalendar.html'))
Fixed

2023-05-24 02:12 UTC, bytehut requested changes

2023-05-24 02:12 UTC, bytehut commented on Backend/sql.js
> +  updateProfilePage,
should be updateProfilePageStatement

2023-05-24 06:32 UTC, bytehut approved these changes
Looks good! Thanks for getting back on the issues.

2023-05-24 06:32 UTC, merged